# Generated by Django 5.2.8 on 2025-11-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Vendido'), (1, 'Em estoque')], default=1, verbose_name='Status'),
        ),
    ]
