# Generated by Django 5.2.8 on 2025-11-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
