# Generated by Django 5.2.8 on 2025-11-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_sale_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
