# Generated by Django 5.2.8 on 2025-11-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_sale_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em estoque'), (0, 'Vendido')], default=1, verbose_name='Status'),
        ),
    ]
